"""TurboMemory integration for ProactiveBotLoop.

This module provides adapter methods for storing and retrieving proactive
learning data from TurboMemoryStore.
"""

from datetime import datetime
from typing import Any, Dict, List, Optional

from loguru import logger

from nanofolks.memory.models import Learning


class ProactiveLearningStore:
    """Adapter for storing proactive learning data in TurboMemory.

    This class provides methods for:
    - Recording proactive decisions
    - Retrieving historical success patterns
    - Updating with user feedback
    """

    def __init__(self, turbo_memory_store):
        """Initialize the proactive learning store.

        Args:
            turbo_memory_store: TurboMemoryStore instance
        """
        self.store = turbo_memory_store
        self.logger = logger.bind(component="ProactiveLearningStore")

    async def add_proactive_learning(
        self,
        bot_name: str,
        original_request: str,
        clarifying_question: str,
        selected_action: str,
        confidence: float,
        user_responded: bool,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> str:
        """Record a proactive decision.

        Args:
            bot_name: Bot that made the decision
            original_request: User's original request
            clarifying_question: Question asked by bot
            selected_action: Action type selected
            confidence: Confidence score (0.0-1.0)
            user_responded: Whether user responded before timeout
            metadata: Additional metadata

        Returns:
            Learning ID
        """
        try:
            # Create learning content
            if user_responded:
                content = (
                    f"Bot {bot_name} asked: '{clarifying_question}' "
                    f"and user responded. Original request: {original_request[:100]}"
                )
            else:
                content = (
                    f"Bot {bot_name} proactively decided to {selected_action} "
                    f"(confidence: {confidence:.2f}) after asking: '{clarifying_question}'. "
                    f"Original request: {original_request[:100]}"
                )

            # Create Learning object
            learning = Learning(
                id="",  # Will be generated by store
                content=content,
                source="self_evaluation",
                sentiment="neutral",
                confidence=confidence,
                recommendation=selected_action,
                metadata={
                    "bot_name": bot_name,
                    "original_request": original_request,
                    "clarifying_question": clarifying_question,
                    "selected_action": selected_action,
                    "user_responded": user_responded,
                    **(metadata or {}),
                },
            )

            # Store in TurboMemory
            learning_id = self.store.create_learning(learning)

            self.logger.debug(f"Recorded proactive learning {learning_id} for {bot_name}")

            return learning_id

        except Exception as e:
            self.logger.error(f"Failed to record proactive learning: {e}")
            raise

    async def get_learnings(
        self,
        bot_name: str,
        intent_type: str,
        limit: int = 5,
    ) -> List[Dict[str, Any]]:
        """Get historical learnings for a bot/intent combination.

        Args:
            bot_name: Bot to get learnings for
            intent_type: Intent type to filter by
            limit: Maximum number of learnings to return

        Returns:
            List of learning records
        """
        try:
            # Get learnings by bot scope
            learnings = self.store.get_learnings_by_bot(
                bot_name=bot_name,
                scope="proactive",
                limit=limit * 2,  # Get more and filter
            )

            # Filter by intent type and format
            results = []
            for learning in learnings:
                metadata = learning.metadata or {}

                # Check if this learning is for the requested intent
                if intent_type in learning.recommendation or intent_type in metadata.get(
                    "selected_action", ""
                ):
                    results.append(
                        {
                            "id": learning.id,
                            "content": learning.content,
                            "confidence": learning.confidence,
                            "success": metadata.get("success"),
                            "user_responded": metadata.get("user_responded"),
                            "created_at": learning.created_at,
                            "metadata": metadata,
                        }
                    )

                    if len(results) >= limit:
                        break

            return results

        except Exception as e:
            self.logger.warning(f"Error retrieving learnings: {e}")
            return []

    async def update_proactive_feedback(
        self,
        room_id: str,
        bot_name: str,
        was_correct: bool,
        user_follow_up: Optional[str] = None,
    ) -> bool:
        """Update learning with user feedback.

        Args:
            room_id: Room ID
            bot_name: Bot that made proactive decision
            was_correct: Whether the decision was correct
            user_follow_up: User's follow-up message

        Returns:
            True if updated successfully
        """
        try:
            # Find recent proactive learning for this bot in this room
            learnings = self.store.get_learnings_by_bot(
                bot_name=bot_name,
                scope="proactive",
                limit=10,
            )

            # Find the most recent one matching this room
            target_learning = None
            for learning in learnings:
                metadata = learning.metadata or {}
                if metadata.get("room_id") == room_id:
                    target_learning = learning
                    break

            if not target_learning:
                self.logger.warning(f"No proactive learning found for {bot_name} in room {room_id}")
                return False

            # Update the learning
            target_learning.metadata["success"] = was_correct
            target_learning.metadata["user_follow_up"] = user_follow_up
            target_learning.metadata["feedback_timestamp"] = datetime.now().isoformat()

            # Update sentiment based on feedback
            if was_correct:
                target_learning.sentiment = "positive"
                target_learning.confidence = min(1.0, target_learning.confidence + 0.1)
            else:
                target_learning.sentiment = "negative"
                target_learning.confidence = max(0.0, target_learning.confidence - 0.1)

            # Save updated learning
            self.store.update_learning(target_learning)

            self.logger.info(
                f"Updated proactive learning {target_learning.id}: correct={was_correct}"
            )

            return True

        except Exception as e:
            self.logger.error(f"Failed to update learning feedback: {e}")
            return False

    async def get_success_rate(
        self,
        bot_name: str,
        action_type: str,
        window_days: int = 30,
    ) -> float:
        """Get success rate for a bot/action combination.

        Args:
            bot_name: Bot name
            action_type: Action type
            window_days: Time window in days

        Returns:
            Success rate (0.0-1.0)
        """
        try:
            learnings = self.store.get_learnings_by_bot(
                bot_name=bot_name,
                scope="proactive",
                limit=100,
            )

            # Filter by action type and time window
            cutoff = datetime.now() - __import__("datetime").timedelta(days=window_days)

            matching = []
            for learning in learnings:
                metadata = learning.metadata or {}
                if action_type in metadata.get("selected_action", ""):
                    if learning.created_at and learning.created_at > cutoff:
                        matching.append(learning)

            if not matching:
                return 0.5  # Neutral if no data

            # Calculate success rate
            successful = sum(1 for l in matching if l.metadata.get("success", False))

            return successful / len(matching)

        except Exception as e:
            self.logger.warning(f"Error calculating success rate: {e}")
            return 0.5


# Convenience function for creating the store
def create_proactive_learning_store(turbo_memory_store) -> Optional[ProactiveLearningStore]:
    """Create a ProactiveLearningStore if TurboMemory is available.

    Args:
        turbo_memory_store: TurboMemoryStore instance

    Returns:
        ProactiveLearningStore or None if no store available
    """
    if turbo_memory_store is None:
        return None

    return ProactiveLearningStore(turbo_memory_store)
